// SPECTRA — DAX Measures for Power BI
// Portfolio Health Dashboard + Client Risk Profile Dashboard
// All measures reference imported tables: DueDaysDaily, RiskPortfolio, Customer, Credits

// ── Portfolio KPIs ──────────────────────────────────────────────────────────

Total Exposure =
SUMX(
    FILTER(RiskPortfolio, RiskPortfolio[rn] = 1),
    RiskPortfolio[totalExposure]
)

On Balance Exposure =
SUMX(
    FILTER(RiskPortfolio, RiskPortfolio[rn] = 1),
    RiskPortfolio[onBalanceExposure]
)

Off Balance Exposure =
SUMX(
    FILTER(RiskPortfolio, RiskPortfolio[rn] = 1),
    RiskPortfolio[TotalOffBalance]
)

Delinquency Rate % =
DIVIDE(
    COUNTROWS(FILTER(DueDaysDaily, DueDaysDaily[DueDays] >= 30)),
    COUNTROWS(DueDaysDaily),
    0
) * 100

Avg Days Past Due =
AVERAGEX(DueDaysDaily, DueDaysDaily[DueDays])

Late Payment Ratio % =
DIVIDE(
    COUNTROWS(FILTER(DueDaysDaily, DueDaysDaily[DueDays] > 0)),
    COUNTROWS(DueDaysDaily),
    0
) * 100

Total Clients =
DISTINCTCOUNT(DueDaysDaily[PersonalID])

Total Active Credits =
DISTINCTCOUNT(Credits[CreditAccount])

// ── Stage Distribution ───────────────────────────────────────────────────────

Stage 1 Exposure =
CALCULATE(
    [Total Exposure],
    RiskPortfolio[Stage] = "1"
)

Stage 2 Exposure =
CALCULATE(
    [Total Exposure],
    RiskPortfolio[Stage] = "2"
)

Stage 3 Exposure =
CALCULATE(
    [Total Exposure],
    RiskPortfolio[Stage] = "3"
)

Stage 1 % =
DIVIDE([Stage 1 Exposure], [Total Exposure], 0) * 100

Stage 2 % =
DIVIDE([Stage 2 Exposure], [Total Exposure], 0) * 100

Stage 3 % =
DIVIDE([Stage 3 Exposure], [Total Exposure], 0) * 100

// ── Provision ────────────────────────────────────────────────────────────────

Total Provision =
SUMX(
    FILTER(RiskPortfolio, RiskPortfolio[rn] = 1),
    RiskPortfolio[CalculatedProvision]
)

Provision Coverage % =
DIVIDE([Total Provision], [On Balance Exposure], 0) * 100

// ── Client Risk Profile (single-client context via slicer) ──────────────────

Client Total Exposure =
CALCULATE(
    [Total Exposure],
    ALLEXCEPT(RiskPortfolio, RiskPortfolio[clientID])
)

Client Current DPD =
CALCULATE(
    MAX(DueDaysDaily[DueDays]),
    ALLEXCEPT(DueDaysDaily, DueDaysDaily[PersonalID])
)

Client Max DPD 12M =
CALCULATE(
    MAX(DueDaysDaily[DueMax1Y]),
    ALLEXCEPT(DueDaysDaily, DueDaysDaily[PersonalID])
)

Client Stage =
CALCULATE(
    LASTNONBLANKVALUE(RiskPortfolio[CalculationDate], MAX(RiskPortfolio[Stage])),
    ALLEXCEPT(RiskPortfolio, RiskPortfolio[clientID])
)

// ── EWI Computed Flags ───────────────────────────────────────────────────────

Clients With Salary Stopped =
COUNTROWS(
    FILTER(
        SUMMARIZE(
            TAccounts,
            TAccounts[NoAccount],
            "last_salary_days",
            DATEDIFF(
                MAXX(
                    FILTER(TAccounts, SEARCH("salary", TAccounts[TDescription1], 1, 0) > 0),
                    TAccounts[Date]
                ),
                TODAY(),
                DAY
            )
        ),
        [last_salary_days] > 30
    )
)

Clients With Overdraft Spike =
COUNTROWS(
    FILTER(
        SUMMARIZE(
            Accounts,
            Accounts[PersonalID],
            "utilization",
            DIVIDE(
                SUMX(Accounts, Accounts[Balance] * -1),
                SUMX(Accounts, Accounts[amountonhold]),
                0
            )
        ),
        [utilization] > 0.8
    )
)

// ── NPL Ratio ─────────────────────────────────────────────────────────────────

NPL Count =
CALCULATE(
    DISTINCTCOUNT(DueDaysDaily[CreditAccount]),
    DueDaysDaily[DueDays] >= 90
)

NPL Ratio % =
DIVIDE([NPL Count], [Total Active Credits], 0) * 100

NPL Ratio Flag =
IF([NPL Ratio %] > 5, "Watch", "Normal")

// ── ECL / IFRS 9 ─────────────────────────────────────────────────────────────

Calculated ECL =
SUMX(
    FILTER(RiskPortfolio, RiskPortfolio[rn] = 1),
    RiskPortfolio[totalExposure] *
    SWITCH(
        RiskPortfolio[Stage],
        1, 0.01,
        2, 0.20,
        1.00
    ) * 0.45
)

ECL Provision Gap =
[Total Provision] - [Calculated ECL]

ECL Gap Flag =
IF([ECL Provision Gap] < 0, "Under-provisioned", "Adequate")

// ── Coverage Ratio ────────────────────────────────────────────────────────────

Coverage Ratio Stage 2 % =
CALCULATE(
    DIVIDE(
        SUM(RiskPortfolio[CalculatedProvision]),
        SUM(RiskPortfolio[totalExposure]),
        0
    ) * 100,
    RiskPortfolio[Stage] = 2,
    FILTER(RiskPortfolio, RiskPortfolio[rn] = 1)
)

Coverage Ratio Stage 3 % =
CALCULATE(
    DIVIDE(
        SUM(RiskPortfolio[CalculatedProvision]),
        SUM(RiskPortfolio[totalExposure]),
        0
    ) * 100,
    RiskPortfolio[Stage] = 3,
    FILTER(RiskPortfolio, RiskPortfolio[rn] = 1)
)

// ── Interest Income at Risk ───────────────────────────────────────────────────

Interest Income at Risk =
SUMX(
    FILTER(RiskPortfolio, RiskPortfolio[Stage] >= 2 && RiskPortfolio[rn] = 1),
    RiskPortfolio[totalExposure] * RiskPortfolio[Effective Interest Rate] / 100
)

At Risk Exposure =
CALCULATE(
    [Total Exposure],
    RiskPortfolio[Stage] >= 2,
    FILTER(RiskPortfolio, RiskPortfolio[rn] = 1)
)

At Risk Exposure % =
DIVIDE([At Risk Exposure], [Total Exposure], 0) * 100

// ── Repayment ─────────────────────────────────────────────────────────────────

Avg Repayment Rate % =
AVERAGEX(
    FILTER(AmortizationPlan, AmortizationPlan[ANUITET] > 0),
    DIVIDE(AmortizationPlan[OTPLATA], AmortizationPlan[ANUITET], 0)
) * 100

Missed Payments Count =
COUNTROWS(FILTER(AmortizationPlan, AmortizationPlan[OTPLATA] = 0 && AmortizationPlan[ANUITET] > 0))

Missed Payment Ratio % =
DIVIDE(
    [Missed Payments Count],
    COUNTROWS(FILTER(AmortizationPlan, AmortizationPlan[ANUITET] > 0)),
    0
) * 100

// ── Card Spend ────────────────────────────────────────────────────────────────

Card Spend Last 30 Days =
CALCULATE(
    SUM(CC_Event_LOG[Ammount]),
    CC_Event_LOG[trans_date] >= TODAY() - 30
)

Card Spend Last 60 Days =
CALCULATE(
    SUM(CC_Event_LOG[Ammount]),
    CC_Event_LOG[trans_date] >= TODAY() - 60 &&
    CC_Event_LOG[trans_date] < TODAY() - 30
)

Card Spend MoM Growth % =
DIVIDE(
    [Card Spend Last 30 Days] - [Card Spend Last 60 Days],
    [Card Spend Last 60 Days],
    0
) * 100

// ── Vintage Analysis ──────────────────────────────────────────────────────────

Delinquency Rate by Vintage % =
DIVIDE(
    CALCULATE(
        DISTINCTCOUNT(DueDaysDaily[CreditAccount]),
        DueDaysDaily[DueDays] >= 30
    ),
    CALCULATE(DISTINCTCOUNT(DueDaysDaily[CreditAccount])),
    0
) * 100

// ── PD by Rating ──────────────────────────────────────────────────────────────

PD Rate % =
DIVIDE(
    CALCULATE(
        DISTINCTCOUNT(RiskPortfolio[clientID]),
        RiskPortfolio[Stage] = 3
    ),
    CALCULATE(
        DISTINCTCOUNT(RiskPortfolio[clientID]),
        FILTER(RiskPortfolio, RiskPortfolio[rn] = 1)
    ),
    0
) * 100

// ── Stage Migration ───────────────────────────────────────────────────────────

Stage Migration Rate % =
VAR _upgraded =
    COUNTROWS(
        FILTER(
            RiskPortfolio,
            RiskPortfolio[Stage] > EARLIER(RiskPortfolio[Stage])
        )
    )
RETURN
DIVIDE(_upgraded, COUNTROWS(RiskPortfolio), 0) * 100

// ── Prediction Scores (from predictions.csv import) ──────────────────────────

Avg PD Score =
AVERAGE(Predictions[pd_score])

High Risk Client Count =
COUNTROWS(FILTER(Predictions, Predictions[pd_score] > 0.65))

Critical Risk Client Count =
COUNTROWS(FILTER(Predictions, Predictions[risk_label] = "Critical" || Predictions[risk_label] = "Default imminent"))

// ── Time Intelligence ─────────────────────────────────────────────────────────

Total Exposure MoM Change % =
VAR _current = [Total Exposure]
VAR _prior =
    CALCULATE(
        [Total Exposure],
        DATEADD('Calendar'[Date], -1, MONTH)
    )
RETURN DIVIDE(_current - _prior, _prior, 0) * 100

NPL Ratio MoM Change % =
VAR _current = [NPL Ratio %]
VAR _prior =
    CALCULATE(
        [NPL Ratio %],
        DATEADD('Calendar'[Date], -1, MONTH)
    )
RETURN _current - _prior
