-- =============================================================================
-- SPECTRA Performance Indexes
-- Generated by improvement.md optimisation pass
-- Run against the SPECTRA database.  Each CREATE is wrapped in an existence
-- check so it is safe to re-run.
-- =============================================================================

USE [SPECTRA];
GO

-- ---------------------------------------------------------------------------
-- 1. Clients(Stage, RiskScore)
--    Speeds up stage-distribution queries, watchlist filtering, and any
--    ORDER BY RiskScore DESC scans on the Clients / Customer table.
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[Clients]')
  AND    name      = N'IX_Clients_Stage_RiskScore'
)
CREATE NONCLUSTERED INDEX [IX_Clients_Stage_RiskScore]
  ON [dbo].[Clients] ([Stage], [RiskScore] DESC)
  INCLUDE ([PersonalID], [Name], [Surname]);
GO

-- ---------------------------------------------------------------------------
-- 2. EWISignals(ClientID)
--    Speeds up per-client early-warning lookups and JOIN to Customer.
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[EWISignals]')
  AND    name      = N'IX_EWISignals_ClientID'
)
CREATE NONCLUSTERED INDEX [IX_EWISignals_ClientID]
  ON [dbo].[EWISignals] ([ClientID])
  INCLUDE ([SignalType], [Score], [CreatedAt]);
GO

-- ---------------------------------------------------------------------------
-- 3. AIGeneratedContent(ClientID, ContentType)
--    Speeds up "fetch latest AI summary for client X of type Y" queries.
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[AIGeneratedContent]')
  AND    name      = N'IX_AIGeneratedContent_ClientID_ContentType'
)
CREATE NONCLUSTERED INDEX [IX_AIGeneratedContent_ClientID_ContentType]
  ON [dbo].[AIGeneratedContent] ([ClientID], [ContentType])
  INCLUDE ([Content], [CreatedAt]);
GO

-- ---------------------------------------------------------------------------
-- 4. EWIPredictions(ClientID)
--    Speeds up per-client ML prediction lookups on the portal and client page.
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[EWIPredictions]')
  AND    name      = N'IX_EWIPredictions_ClientID'
)
CREATE NONCLUSTERED INDEX [IX_EWIPredictions_ClientID]
  ON [dbo].[EWIPredictions] (client_id)
  INCLUDE (risk_score, deterioration_risk, run_date);
GO

-- ---------------------------------------------------------------------------
-- 5. EWIRecommendations(ClientID, IsActioned)
--    Speeds up "open recommendations for client X" queries used by the
--    action engine and early-warnings dashboard.
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[EWIRecommendations]')
  AND    name      = N'IX_EWIRecommendations_ClientID_IsActioned'
)
CREATE NONCLUSTERED INDEX [IX_EWIRecommendations_ClientID_IsActioned]
  ON [dbo].[EWIRecommendations] (client_id, is_actioned)
  INCLUDE (recommendation_type, created_at);
GO

-- ---------------------------------------------------------------------------
-- 6. RiskPortfolio(Stage)
--    Speeds up stage-distribution aggregations (getPortfolioKPIs stage2_pct,
--    stage3_pct), watchlist counts, and ECL roll-rate queries that filter or
--    GROUP BY Stage.  Uses INCLUDE to cover CalculationDate + clientID so
--    the stage-filter + date-filter pattern is fully index-covered.
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[RiskPortfolio]')
  AND    name      = N'IX_RiskPortfolio_Stage'
)
CREATE NONCLUSTERED INDEX [IX_RiskPortfolio_Stage]
  ON [dbo].[RiskPortfolio] ([Stage])
  INCLUDE ([clientID], [CalculationDate], [totalExposure]);
GO

-- ---------------------------------------------------------------------------
-- 7. ECLProvisions(client_id, calculated_at)
--    Covers the ROW_NUMBER() OVER (PARTITION BY client_id ORDER BY calculated_at DESC)
--    pattern in getTotalECLProvisions() and latest-provision lookups.
--    (Also created in ecl_provisions_table.sql DDL — safe to re-run.)
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[ECLProvisions]')
  AND    name      = N'IX_ECLProvisions_ClientID_CalculatedAt'
)
CREATE NONCLUSTERED INDEX [IX_ECLProvisions_ClientID_CalculatedAt]
  ON [dbo].[ECLProvisions] (client_id, calculated_at DESC)
  INCLUDE (stage, provision_amount);
GO

-- ---------------------------------------------------------------------------
-- 8. RecoveryCases(client_id, opened_at)
--    Covers getActiveRecoveryCase() (WHERE client_id=X AND status='Open' ORDER BY opened_at DESC)
--    and getRecoveryCaseHistory().
--    (Also created in recovery_tables.sql DDL — safe to re-run.)
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[RecoveryCases]')
  AND    name      = N'IX_RecoveryCases_ClientID_OpenedAt'
)
CREATE NONCLUSTERED INDEX [IX_RecoveryCases_ClientID_OpenedAt]
  ON [dbo].[RecoveryCases] (client_id, opened_at DESC)
  INCLUDE (stage, status, assigned_to);
GO

-- ---------------------------------------------------------------------------
-- 9. CreditCommitteeLog(client_id, escalated_at)
--    Covers getCommitteeLog() SELECT TOP 50 WHERE client_id=X ORDER BY escalated_at DESC.
--    (Also created in committee_log_table.sql DDL — safe to re-run.)
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[CreditCommitteeLog]')
  AND    name      = N'IX_CreditCommitteeLog_ClientID_EscalatedAt'
)
CREATE NONCLUSTERED INDEX [IX_CreditCommitteeLog_ClientID_EscalatedAt]
  ON [dbo].[CreditCommitteeLog] (client_id, escalated_at DESC)
  INCLUDE (decision, escalated_by);
GO

-- ---------------------------------------------------------------------------
-- 10. DueDaysDaily(PersonalID, CreditAccount, dateID)
--     The existing IX_DueDaysDaily_PersonalID_dateID index (recommended_indexes.sql)
--     lacks CreditAccount, which is used in every
--     ROW_NUMBER() OVER (PARTITION BY CreditAccount) de-duplication query.
--     Without this column the engine cannot satisfy the window function from
--     the index alone and falls back to a sort + table scan.
--     DueDays is INCLUDEd to cover the ORDER BY TRY_CAST(DueDays AS FLOAT) clause.
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[DueDaysDaily]')
  AND    name      = N'IX_DueDaysDaily_PersonalID_CreditAccount_dateID'
)
CREATE NONCLUSTERED INDEX [IX_DueDaysDaily_PersonalID_CreditAccount_dateID]
  ON [dbo].[DueDaysDaily] ([PersonalID], [CreditAccount], [dateID])
  INCLUDE ([DueDays]);
GO

-- ---------------------------------------------------------------------------
-- 11. TAccounts(Date, NoAccount)
--     getEWISummary() scans TAccounts up to 5× per call (salary_stopped,
--     overdraft_spike, card_high, consec_lates CTEs). Date is stored as a
--     string but all WHERE clauses filter on it with >= comparisons.
--     Adding this index turns those 5 full-table scans into index seeks.
-- ---------------------------------------------------------------------------
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE  object_id = OBJECT_ID(N'[dbo].[TAccounts]')
  AND    name      = N'IX_TAccounts_Date_NoAccount'
)
CREATE NONCLUSTERED INDEX [IX_TAccounts_Date_NoAccount]
  ON [dbo].[TAccounts] ([Date], [NoAccount])
  INCLUDE ([Amount]);
GO

PRINT 'SPECTRA performance indexes applied successfully.';
GO
